### PR TITLE
Make SellingPoints floating image work better with HackerTestimonials

### PR DESCRIPTION
**Pull request by rosslh**
## Proposed Change

Make SellingPoints floating image work better with HackerTestimonials

### How did you do this?

Resize it and hide it at a certain width

### Why are you choosing this approach?

To make the white-space around this image look good

### Any open questions you want to ask code reviewers?

No

### List of changes:

  - Make SellingPoints floating image work better with HackerTestimonials

## Pull Request Checklist:

  - [x] My submission passes all tests.
  - [x] I have lint my code locally prior to submission.
  - [x] I have written new unit tests for my core changes (where applicable).
  - [x] I have written browser integration tests for my core changes (where application).
  - [x] I have referenced all useful information (issues, tasks, etc) in the pull request.

### CODE REVIEW

**Comment by RobertWSaunders** [comment]
Deploy preview for *qhacks-website* ready!

Built with commit b78a7e70ee0dbd000abd77f4fd4a98095f3c88df

https://deploy-preview-199--qhacks-website.netlify.com

**Comment by RobertWSaunders** [comment]
Instead of removing lets just make smaller?

**Comment by rosslh** [comment]
@RobertWSaunders gave that a try, lmk what you think

**Comment by RobertWSaunders** [comment]
Yep smaller looks good!

**Pull request merged**
