### PR TITLE
Fix MobileMenu component to match mocks

### PR DESCRIPTION
**Pull request by joeytepp**
## Proposed Change
Change the mobile menu to better match the mocks

Fixes: #162

### How did you do this?
Minor CSS tweaks

### Why are you choosing this approach?
To match the mocks!

### Any open questions you want to ask code reviewers?
No

### List of changes:

  - Change margins of bottom cubes
  - Change font weight of cubes
  - Update snapshots

## Pull Request Checklist:

  - [x] My submission passes all tests.
  - [x] I have lint my code locally prior to submission.
  - [x] I have written new unit tests for my core changes (where applicable).
  - [x] I have written browser integration tests for my core changes (where application).
  - [x] I have referenced all useful information (issues, tasks, etc) in the pull request.

### CODE REVIEW

**Comment by RobertWSaunders** [comment]
Deploy preview for *qhacks-website* ready!

Built with commit b7a9c8502a318aa3e11506eba3de08aae46874d2

https://deploy-preview-188--qhacks-website.netlify.com

**Comment by RobertWSaunders** [comment]
I think you need to rebase on `dev`, the preview has some out of date stuff.

**Comment by joeytepp** [comment]
Rebased!

**Comment by RobertWSaunders** [comment]
Removed the rule that required all code owners to review!

**Pull request merged**
